# Site settings
title: Alexander DÃ¼mont
email: alexander_duemont@web.de
description: > 
  Personal solutions to little programming problems.

baseurl: "" 
url: "http://blog.newtork.de" 
headline: "Newt<small>|</small>ork"

# style
custom_css: "newtork.css"

# Media
github_username: newtork

# comments
isso_tld: "//comments.newtork.de/"
isso_src: "//comments.newtork.de/js/embed.min.js"

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

gems:
  - jekyll-gist
  - jekyll-redirect-from

whitelist:
  - jekyll-gist
  - jekyll-redirect-from
